export { vuetify } from './theme'
export { i18n } from './i18n'
export { defineAbilitiesFor, caslPlugin } from './casl'
export { notify } from './notifications'
export { toastPlugin } from './toast'
export { validationPlugin } from './validation'
export { axiosInstance } from './axios'
export { chartsPlugin, apexChartsConfig } from './charts'
export { prismPlugin } from './prism'
